### ISSUE TITLE
error when using a different aws region

### ISSUE THREAD

**Issue by TopRoupi** [mucsi96/postgres-backup-tool#1]
![image](https://github.com/mucsi96/postgres-backup-tool/assets/38011914/79f27639-0198-4365-be6d-8f028ea3b952)

**Comment by mucsi96** [comment]
HI! Would you be able to help with contribution a fix for this?

**Comment by TopRoupi** [comment]
no, im not familiar with java.

**Comment by mucsi96** [comment]
Now you can provide region using `DB_BACKUP_REGION` environment variable. So the issues should be resolved

**Comment by mucsi96** [comment]
Actually I have renamed the variables to make it more explicit

![image](https://github.com/mucsi96/postgres-backup-tool/assets/3163392/0d15a220-6f28-4832-baf2-8164e5a7301e)
